### ISSUE TITLE
Can click 'remember me' box

### ISSUE THREAD

**Issue by EdsonMorfin** [OswaldoPineda/Today_I_learned#38]
## Issue Description:
Remember me option only work if you click the text but not the box
## Behavior Example:
Click 'remember me' text
## Benefit:
User experience

## Screenshots: (If apply)
<img width="551" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/74a50f8e-7702-43c4-ac72-fa988e302a32">

**Comment by OswaldoPineda** [comment]
Fixed on #63
