### ISSUE TITLE
Login: Unhashed password and double value in 'remember_me'

### ISSUE THREAD

**Issue by EdsonMorfin** [OswaldoPineda/Today_I_learned#39]
## Issue Description:
The password is send without hashing and remember_me value acts weird
## Screenshots: (If apply)
<img width="592" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/cb4d1609-7160-4335-a3c6-e209a86e3004">

**Comment by OswaldoPineda** [comment]
not an issue, the remember_me values are an expected behavior.
