### ISSUE TITLE
Custom e-mail for mailer

### ISSUE THREAD

**Issue by EdsonMorfin** [OswaldoPineda/Today_I_learned#40]
## Issue Description:
I believe mail experience would be better if the sender email was custom, something like 'no-reply@todayilearned.dev' 
## Screenshots: (If apply)
<img width="486" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/b0cefd3a-1b1e-4868-a09f-e63e6108c2ef">

**Comment by OswaldoPineda** [comment]
Fixed on #49 49
