### ISSUE TITLE
Layout and security issue

### ISSUE THREAD

**Issue by EdsonMorfin** [OswaldoPineda/Today_I_learned#41]
## Issue Description:
Email field shows up weird and I believe that it would be best if it displays a message like ' If the email exists we will send an password reset message ' instead of ' email not found ', this can cause security breaches because you give one of the two necessary data to log in
## Screenshots: (If apply)
<img width="904" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/f0cd001b-f523-4eca-81e5-cc72149b5c49">

**Comment by OswaldoPineda** [comment]
Fixed on #53
