### ISSUE TITLE
layout and lenght issue with new post

### ISSUE THREAD

**Issue by EdsonMorfin** [OswaldoPineda/Today_I_learned#42]
## Issue Description:
I would recomend to put a max length rule to avoid unexpected issues related to too long posts
## Screenshots: (If apply)
<img width="1238" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/9c8b1678-5a21-4b3f-bf44-b4027b01d228">
<img width="1257" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/7ba7ca33-9c50-46cd-87c4-e0ef061903eb">
<img width="1275" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/86afd809-152d-46ec-8b9c-025e8e147dea">

**Comment by OswaldoPineda** [comment]
Fixed on: #44
