### ISSUE TITLE
feedback section

### ISSUE THREAD

**Issue by EdsonMorfin** [OswaldoPineda/Today_I_learned#43]
## Issue Description:
since is a WIP page I would add a feedback section 
## Screenshots: (If apply)
<img width="275" alt="image" src="https://github.com/OswaldoPineda/Today_I_learned/assets/73849076/b0a95380-efa3-4ec4-8c39-4726d2f3d79d">

**Comment by JuanequeX** [comment]
this ticket was solved in #57

**Comment by JuanequeX** [comment]
Was decided to relocate this feedback channel in the footer
